title: Tessera
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Tessera example webpage
baseurl: "/Tessera"
url: ""
github_username: itszariep

# Build settings
remote_theme: itszariep/tessera

social_links:
  - name: GitHub
    url: https://github.com/itszariep
    icon: github

plugins:
  - jekyll-paginate

paginate: 9
paginate_path: "/page:num/"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      image: /preview.jpg

date_format: "%d/%m/%Y"